source 'https://github.com/CocoaPods/Specs'

platform :ios, '9.0'
use_frameworks!

# Add Application pods here
def app_pods
    pod 'Alamofire', '~> 4.0'
    pod 'AlamofireImage', '~> 3.0'
    pod 'AsyncSwift', '~> 2.0'
    pod 'Crashlytics'
    pod 'Device', '~> 2.0'
    pod 'Decodable', '~> 0.5'
    pod 'DynamicColor', '~> 3.0'
    pod 'Eureka', '~> 2.0.0-beta.1'
    pod 'Fabric', '~> 1.6'
    pod 'KeychainAccess', '~> 3.0'
    pod 'NVActivityIndicatorView', '~> 3.0'
    pod 'Opera', :git => 'https://github.com/xmartlabs/Opera.git', :branch => 'Swift3'
    pod 'R.swift', '~> 3.0'
    pod 'RealmSwift', '~> 2.0'
    pod 'Result', '~> 3.0'
    pod 'RxAlamofire', '~> 3.0'
    pod 'RxCocoa', '~> 3.0'
    pod 'RxSwift', '~> 3.0'
    pod 'SwiftDate', '~> 4.0'
    pod 'WebLinking', :git => 'https://github.com/kylef/WebLinking.swift', :branch => 'master'
    pod 'XLSwiftKit', '~> 2.0'
end

def testing_pods
    pod 'Quick', '~> 1.0'
    pod 'Nimble', '~> 5.0'
end

target 'XLProjectName' do
    app_pods
end

target 'XLProjectName-Staging' do
    app_pods
end

target 'Tests' do
  testing_pods
end

target 'UITests' do
    testing_pods
end

post_install do |installer|
    puts 'Removing static analyzer support'
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['OTHER_CFLAGS'] = "$(inherited) -Qunused-arguments -Xanalyzer -analyzer-disable-all-checks"
        end
    end
end
